import { ReactNode } from "react";
import type { Metadata } from "next";
import { Libre_Franklin, Lora } from "next/font/google";
import { Header } from "./Header";
import { Footer } from "./Footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontPrimary = Libre_Franklin({
  subsets: ["cyrillic", "latin"],
  display: "swap",
  variable: "--font-primary",
});

const fontSecondary = Lora({
  subsets: ["cyrillic", "latin"],
  display: "swap",
  variable: "--font-secondary",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html
      lang="ru"
      className={`${fontPrimary.variable} ${fontSecondary.variable} h-full`}
    >
      <body className="flex flex-col h-full">
        <Header />
        <main id="main-content" className="flex-1">
          <div className="mt-[var(--app-header-height)]">{children}</div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
