import { ReactNode } from "react";
import type { Metadata } from "next";
import { Vollkorn } from "next/font/google";
import { Header } from "./Header";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = Vollkorn({
  subsets: ["cyrillic", "latin"],
  display: "swap",
  variable: "--font-serif",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ru" className={font.className}>
      <body>
        <Header />
        <main id="main-content">
          <div className="sm:mt-[var(--app-header-height)]">{children}</div>
        </main>
      </body>
    </html>
  );
}
