import {БелорускиComponent} from "./jsx_files/БелорускиComponent.jsx"; 
import {ПолькиComponent} from "./jsx_files/ПолькиComponent.jsx"; 
import {ИжоркиComponent} from "./jsx_files/ИжоркиComponent.jsx"; 
import {АрмянкиComponent} from "./jsx_files/АрмянкиComponent.jsx"; 
import {ЕврейкиComponent} from "./jsx_files/ЕврейкиComponent.jsx"; 
import {УкраинкиComponent} from "./jsx_files/УкраинкиComponent.jsx"; 
import {ЛитовкиComponent} from "./jsx_files/ЛитовкиComponent.jsx"; 
import {НемкиComponent} from "./jsx_files/НемкиComponent.jsx"; 
import {ГречанкиComponent} from "./jsx_files/ГречанкиComponent.jsx"; 
export { БелорускиComponent, ПолькиComponent, ИжоркиComponent, АрмянкиComponent, ЕврейкиComponent, УкраинкиComponent, ЛитовкиComponent, НемкиComponent, ГречанкиComponent};